// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 06 Jan 2016 00:34:38 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

int PaStreamCallback_9f475638(void* input, void* output, unsigned long int frameCount, PaStreamCallbackTimeInfo* timeInfo, unsigned long int statusFlags, void* userData) {
	return streamCallback9F475638(input, output, frameCount, timeInfo, statusFlags, userData);
}

void PaStreamFinishedCallback_ec352180(void* userData) {
	streamFinishedCallbackEC352180(userData);
}

