// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 04 Sep 2016 02:34:29 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include <portaudio.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// PaStreamCallback_615600db is a proxy for callback PaStreamCallback.
int PaStreamCallback_615600db(void* input, void* output, unsigned long int frameCount, PaStreamCallbackTimeInfo* timeInfo, unsigned long int statusFlags, void* userData);

// PaStreamFinishedCallback_d2bb8f82 is a proxy for callback PaStreamFinishedCallback.
void PaStreamFinishedCallback_d2bb8f82(void* userData);

