// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 23 Jan 2016 21:33:29 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include <portaudio.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// PaStreamCallback_9f475638 is a proxy for callback PaStreamCallback.
int PaStreamCallback_9f475638(void* input, void* output, unsigned long int frameCount, PaStreamCallbackTimeInfo* timeInfo, unsigned long int statusFlags, void* userData);

// PaStreamFinishedCallback_ec352180 is a proxy for callback PaStreamFinishedCallback.
void PaStreamFinishedCallback_ec352180(void* userData);

