// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 06 Jan 2016 00:34:38 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

package portaudio

/*
#cgo pkg-config: portaudio-2.0
#include <portaudio.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// ErrorCode as declared in portaudio/portaudio.h:104
type ErrorCode int

// ErrorCode enumeration from portaudio/portaudio.h:104
const (
	PaNoError                               ErrorCode = C.paNoError
	PaNotInitialized                        ErrorCode = C.paNotInitialized
	PaUnanticipatedHostError                ErrorCode = C.paUnanticipatedHostError
	PaInvalidChannelCount                   ErrorCode = C.paInvalidChannelCount
	PaInvalidSampleRate                     ErrorCode = C.paInvalidSampleRate
	PaInvalidDevice                         ErrorCode = C.paInvalidDevice
	PaInvalidFlag                           ErrorCode = C.paInvalidFlag
	PaSampleFormatNotSupported              ErrorCode = C.paSampleFormatNotSupported
	PaBadIODeviceCombination                ErrorCode = C.paBadIODeviceCombination
	PaInsufficientMemory                    ErrorCode = C.paInsufficientMemory
	PaBufferTooBig                          ErrorCode = C.paBufferTooBig
	PaBufferTooSmall                        ErrorCode = C.paBufferTooSmall
	PaNullCallback                          ErrorCode = C.paNullCallback
	PaBadStreamPtr                          ErrorCode = C.paBadStreamPtr
	PaTimedOut                              ErrorCode = C.paTimedOut
	PaInternalError                         ErrorCode = C.paInternalError
	PaDeviceUnavailable                     ErrorCode = C.paDeviceUnavailable
	PaIncompatibleHostApiSpecificStreamInfo ErrorCode = C.paIncompatibleHostApiSpecificStreamInfo
	PaStreamIsStopped                       ErrorCode = C.paStreamIsStopped
	PaStreamIsNotStopped                    ErrorCode = C.paStreamIsNotStopped
	PaInputOverflowed                       ErrorCode = C.paInputOverflowed
	PaOutputUnderflowed                     ErrorCode = C.paOutputUnderflowed
	PaHostApiNotFound                       ErrorCode = C.paHostApiNotFound
	PaInvalidHostApi                        ErrorCode = C.paInvalidHostApi
	PaCanNotReadFromACallbackStream         ErrorCode = C.paCanNotReadFromACallbackStream
	PaCanNotWriteToACallbackStream          ErrorCode = C.paCanNotWriteToACallbackStream
	PaCanNotReadFromAnOutputOnlyStream      ErrorCode = C.paCanNotReadFromAnOutputOnlyStream
	PaCanNotWriteToAnInputOnlyStream        ErrorCode = C.paCanNotWriteToAnInputOnlyStream
	PaIncompatibleStreamHostApi             ErrorCode = C.paIncompatibleStreamHostApi
	PaBadBufferPtr                          ErrorCode = C.paBadBufferPtr
)

// HostApiTypeId as declared in portaudio/portaudio.h:240
type HostApiTypeId uint

// HostApiTypeId enumeration from portaudio/portaudio.h:240
const (
	PaInDevelopment   HostApiTypeId = C.paInDevelopment
	PaDirectSound     HostApiTypeId = C.paDirectSound
	PaMME             HostApiTypeId = C.paMME
	PaASIO            HostApiTypeId = C.paASIO
	PaSoundManager    HostApiTypeId = C.paSoundManager
	PaCoreAudio       HostApiTypeId = C.paCoreAudio
	PaOSS             HostApiTypeId = C.paOSS
	PaALSA            HostApiTypeId = C.paALSA
	PaAL              HostApiTypeId = C.paAL
	PaBeOS            HostApiTypeId = C.paBeOS
	PaWDMKS           HostApiTypeId = C.paWDMKS
	PaJACK            HostApiTypeId = C.paJACK
	PaWASAPI          HostApiTypeId = C.paWASAPI
	PaAudioScienceHPI HostApiTypeId = C.paAudioScienceHPI
)

// StreamCallbackResult as declared in portaudio/portaudio.h:707
type StreamCallbackResult uint

// StreamCallbackResult enumeration from portaudio/portaudio.h:707
const (
	PaContinue StreamCallbackResult = C.paContinue
	PaComplete StreamCallbackResult = C.paComplete
	PaAbort    StreamCallbackResult = C.paAbort
)
