// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 06 Jan 2016 04:08:45 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package portaudio provides Go bindings for libportaudio.
*/
package portaudio
