// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 05 Mar 2016 02:20:58 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package portaudio provides Go bindings for libportaudio.
*/
package portaudio
